### ISSUE TITLE
anonymous delegates

### ISSUE THREAD

**Issue by mhn65536** [thomaslevesque/WeakEvent#29]
As far as i can see, the code fails when using anonymous delegates, that capture variables, because those create a new class. I'm not very good at explaining, but you sure got the idea.

int i = 0;
Source.Subscribe((o,e) => Test(i));

You could provide an overload to Subscribe that allows you to specify the hook object instead of deriving it from delegate.Target. Obviously it'd most likely require the use of ConditionalWeakTable.

**Comment by thomaslevesque** [comment]
Hi @mhn65536,

The reason why it doesn't work is because you're not keeping a reference to the anonymous delegate. Since WeakEvent also doesn't keep a reference to it (that's the whole point!), it gets garbage collected.

> You could provide an overload to Subscribe that allows you to specify the hook object instead of deriving it from delegate.Target. Obviously it'd most likely require the use of ConditionalWeakTable.

I'm not sure I understand what you have in mind... What would your code look like with that overload?

**Comment by thomaslevesque** [comment]
Ah, I understand now. You mean something like this?

```csharp
Source.Subscribe(this, (o,e) => Test(i));
```

And as long as `this` is alive, the handler would stay alive as well?

**Comment by mhn65536** [comment]
yes that was why i meant.

**Comment by thomaslevesque** [comment]
Seems feasible, and a good idea, I'll think about it. Thanks for the suggestion!

**Comment by thomaslevesque** [comment]
I have implemented this in [this branch]. (https://github.com/thomaslevesque/WeakEvent/tree/lifetime-object). If I go ahead and merge it, I'll have to drop support for target frameworks that don't have `ConditionalWeakTable`:
- .NET 3.5 (not a big deal)
- .NET Standard 1.1 (1.3 will be supported instead), which means Windows 8.0/8.1 UWP apps. Slightly more annoying, but probably not a big issue either.

However, now that it's done, I realize that this feature can only be used by directly manipulating the `WeakEventSource`, which makes it much less useful IMO... The typical usage is to keep the `WeakEventSource` object private and expose it via a normal event, so the subscriber can't specify a lifetime object. To expose the functionality, the event publisher will have to expose Subscribe/Unsubscribe methods instead of a normal event.

@mhn65536 what use case did you have in mind?

**Comment by thomaslevesque** [comment]
BTW @mhn65536, since you seemed to have an idea of how to implement this, feel free to review the PR (https://github.com/thomaslevesque/WeakEvent/pull/33) if you like!
