### ISSUE TITLE
operator overloading

### ISSUE THREAD

**Issue by mhn65536** [thomaslevesque/WeakEvent#30]
You could use operator overloading to mimic the use(+= /-=) of normal events. 
Also this would allow you to create an instance only on demand, reducing the cost of unused events, as the + operator can return a new instance if used on a null.

**Comment by thomaslevesque** [comment]
Hi @mhn65536,

Do you mean something like this?

```
private readonly WeakEventSource<MyEventArgs> _myEventSource;
public event EventHandler<MyEventArgs> MyEvent
{
    add { _myEventSource += value; }
    remove { _myEventSource -= value; }
}
```

I like the idea!

**Comment by thomaslevesque** [comment]
> Also this would allow you to create an instance only on demand, reducing the cost of unused events, as the + operator can return a new instance if used on a null.

That's an interesting point, and could easily be implemented, but it raises a few issues:

- It encourages a usage pattern where the `WeakEventSource` object can be null. This means you have to check whether it's null before raising the event. This is easily done with `_myEventSource?.Raise(...)`, but if you're stuck on an older version of C#, you have to do this instead:

    ```csharp
    var source = _myEventSource; // take a copy to avoid race conditions
    if (source != null)
        source.Raise(...);
    ```

    Which is easy to get wrong for junior developers. (actually the same problem exists for normal events).

- What should happen when you remove the last handler with `-=`? Should it return null?
- What happens if two threads try to add a handler at the same time? If the `WeakEventSource` instance is already created, the case is already handled internally. But if not, both threads will create an instance of `WeakEventSource`, and the last one who writes it to the field "wins"; the other subscription is lost. To avoid that, you would need a lock around the `_myEventSource += value`, which makes the new syntax much less compelling...

So, maybe I'll implement the `+=`/`-=` syntax, but the `WeakEventSource` will still have to be initialized beforehand.

About the cost of unused events, I might be able to improve things... I'll look into it.

**Comment by thomaslevesque** [comment]
> So, maybe I'll implement the `+=`/`-=` syntax, but the `WeakEventSource` will still have to be initialized beforehand.

The more I think about it, the less I'm convinced it's a good idea... Objects that support this syntax typically allow null values, but for the reason I mentioned, it's not possible in this case. So it would be counter-intuitive to support this syntax and not allow the `WeakEventSource` to initially be null.

Still, thanks for the suggestion, it was an interesting idea!

I'll wait a bit before closing the issue in case you have counter-arguments :wink:

> About the cost of unused events, I might be able to improve things... I'll look into it.

I split this into a separate issue: https://github.com/thomaslevesque/WeakEvent/issues/31

**Comment by mhn65536** [comment]
I declared the EventSource as a struct. Since you usually do not pass the Source around it shouldn't be a problem. At least in my case i can garuantee that i don't abuse my own code. That resolves the issue with having to create an instance first.

When the Dictionary or List in the Source is null, you lock the type whilst creating it. It's a bottleneck, but an unproblematic one. 

When the Dictionary or List exists, you lock that to make things threadsafe.

The only downside of that approach is, that when you pass an unitialized source, you'd to do it by ref.

**Comment by mhn65536** [comment]
>     * It encourages a usage pattern where the `WeakEventSource` object can be null. This means you have to check whether it's null before raising the event. 

It is the normal behavoir with events...

>       var source = _myEventSource; // take a copy to avoid race conditions
>       if (source != null)
>           source.Raise(...);
>       ```

You could declare it an extension method, to encapsulate this. As fr as i know, those can be safely called on nulls.

>     * What should happen when you remove the last handler with `-=`? Should it return null?

Possibly, but you could leave it initialized for sake of simplicity.

**Comment by thomaslevesque** [comment]
> I declared the EventSource as a struct. Since you usually do not pass the Source around it shouldn't be a problem. At least in my case i can garuantee that i don't abuse my own code. That resolves the issue with having to create an instance first.

Yes, I thought about that. Unfortunately, it wouldn't work when using the `Subscribe`/`Unsubscribe` methods on a read-only `WeakEventSource` field (which is currently the typical way to use it), because the compiler would make a defensive copy of the struct before calling the method, so the original struct would not be modified and would still have a null handler collection. I'm afraid that's too much of a breaking change to take. The fix would be easy (just remove the `readonly` modifier), but the problem could go undetected for a while, since it would still compile fine.

Unless I remove the `Subscribe`/`Unsubscribe` methods, to make the breaking change obvious. But that would be annoying for current users...

> When the Dictionary or List in the Source is null, you lock the type whilst creating it. It's a bottleneck, but an unproblematic one.

In fact, I already implemented that yesterday. No need for locking. https://github.com/thomaslevesque/WeakEvent/commit/0f374ef0badebd83fe46421b05082a8c97c6afa4

> When the Dictionary or List exists, you lock that to make things threadsafe.

That was already in place.

> The only downside of that approach is, that when you pass an unitialized source, you'd to do it by ref.

What do you mean?

**Comment by mhn65536** [comment]
I agree, it would break the current usage and therefore is not feasible.

> What do you mean?

I meant if you pass a struct by value and create the inner List, it will not be reflrected on the original...

**Comment by thomaslevesque** [comment]
> I meant if you pass a struct by value and create the inner List, it will not be reflrected on the original...

Yes, but you can't pass by reference to an operator...

Anyway, it seemed like a great idea, and I would have loved to implement it, but it has too many issues... Thanks anyway for the suggestion!
