### ISSUE TITLE
Different behavior of standard event and WeakEventSource

### ISSUE THREAD

**Issue by JindrichBabica** [thomaslevesque/WeakEvent#43]
Hello,
I have found following article about weak event patterns: https://www.codeproject.com/Articles/29922/Weak-Events-in-C#heading0013

There is an interesting point, try to find the text: "A possible problem here is that someone might try to attach an anonymous method as an event handler that captures a variable. ..."

I supposed that it must be general problem of similar implementation. So I tried to test your implementation using following code:

    public class MyClass
    {
        private readonly WeakEventSource<EventArgs> _myEventSource = new WeakEventSource<EventArgs>();

        public event EventHandler<EventArgs> WeakExecuted
        {
            add => _myEventSource.Subscribe(value);
            remove => _myEventSource.Unsubscribe(value);
        }

        public event EventHandler StrongExecuted;

        public void Execute()
        {
            _myEventSource.Raise(this, EventArgs.Empty);
            StrongExecuted?.Invoke(this, EventArgs.Empty);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            MyClass x = new MyClass();
            RegisterWeakHandler(x);
            RegisterStrongHandler(x);
            System.GC.Collect();
            x.Execute();
        }

        private static void RegisterWeakHandler(MyClass x)
        {
            x.WeakExecuted += (s, a) => { OnWeakExecuted(x, a); };
        }

        private static void RegisterStrongHandler(MyClass x)
        {
            x.StrongExecuted += (s, a) => { OnStrongExecuted(x, a); };
        }

        private static void OnWeakExecuted(object sender, EventArgs e)
        {
            Console.WriteLine("OnWeakExecuted");
        }

        private static void OnStrongExecuted(object sender, EventArgs e)
        {
            Console.WriteLine("OnStrongExecuted");
        }
    }

It seems that only OnStrongExecuted is written to the console. It implies that normal event behaves in a little bit different way than your WeakEventSource. Do you know about this difference? It could be crucial for some usages. Is there any solution for the problem? The mentioned article shows how  to detect the situation.

**Comment by thomaslevesque** [comment]
Hi @JindrichBabica,

> It implies that normal event behaves in a little bit different way than your WeakEventSource

Of course it does! What would be the point if it behaved exactly the same? :wink:

> Do you know about this difference?

Yes, I do.

> It could be crucial for some usages. Is there any solution for the problem? The mentioned article shows how to detect the situation.

Well, it's not really a "problem", as I see it. It behaves as expected: there's no reference to the handler's target, so it's collected, so it's not called when the event is raised.
Detecting it to throw an exception like SmartWeakEvent does isn't a good option, I think, because there are legitimate scenarios where you'd want to subscribe with an anonymous method.

If you subscribe with an anonymous method, it's your responsibility to keep the handler alive as long as necessary. There are two ways to do that:

- Keep a reference to the handler somewhere (e.g. in a field of your class)
- Use the `Subscribe` overload that accepts a `lifetimeObject`; this will keep the handler alive as long as the lifetime object is alive. Of course, you can't do that if you subscribe through a CLR event like your `WeakExecuted` event, because you don't have access to that overload. `MyClass` would need to expose a `Subscribe` method that accepts a lifetime object.

**Comment by JindrichBabica** [comment]
Sure that a different behaviour is expected :) 
Let me explain what I expected. I wanted to replace the standard event with the WeakEventSource. But because of the described problem it is not so straightforward. The change could break some functionality. Moreover the question is whether developer expects such behaviour. It would be nice to have a note about it in readme to be sure that developers know the about it.
Nevertheless thank you for your comments and the package.

**Comment by thomaslevesque** [comment]
Yes, it's not just a drop-in replacement. It can be in some cases, but not when you're using anonymous handlers. I guess I could add a note somewhere.

**Comment by thomaslevesque** [comment]
I added a note to the README. Thanks for the suggestion!
